/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

/**
 *
 * @author alejo
 */
public class MDILogin extends javax.swing.JFrame {

    /**
     * Creates new form MDILogin
     */
    public MDILogin() {
        initComponents();
        getRootPane().setDefaultButton(jButton1);
        
        // --- Premium styling ---
        java.awt.Color gold = new java.awt.Color(212, 175, 55);
        java.awt.Color darkBg = new java.awt.Color(17, 24, 39);
        java.awt.Font boldFont = jButton1.getFont().deriveFont(java.awt.Font.BOLD, 14f);
        
        // Hotel title in gold
        lbHotelGales.setForeground(gold);
        
        // "BIENVENIDO" in gold
        lbBienvenido.setForeground(gold);
        lbBienvenido.setText("BIENVENIDO");
        lbBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        
        // "Iniciar Sesion" button — gold style
        jButton1.setBackground(gold);
        jButton1.setForeground(darkBg);
        jButton1.setFont(boldFont);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                jButton1.setBackground(new java.awt.Color(241, 196, 15));
                jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                jButton1.setBackground(gold);
            }
        });
        
        // "Crear cuenta" button — outline gold
        jButton2.setBackground(darkBg);
        jButton2.setForeground(gold);
        jButton2.setFont(boldFont);
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(gold, 1));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                jButton2.setBackground(gold);
                jButton2.setForeground(darkBg);
                jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                jButton2.setBackground(darkBg);
                jButton2.setForeground(gold);
                jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(gold, 1));
            }
        });
        
        // "Recordarme" checkbox — brighter for dark bg
        chkRecordarme.setForeground(java.awt.Color.WHITE);
        
        // Hide auto-generated text on background image label
        jLabel1.setText("");
        // --- end premium styling ---
        
        // Add component listener to center content when window is resized
        addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                centerContent();
            }
        });
        
        // Add window state listener to handle maximization
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            @Override
            public void windowStateChanged(java.awt.event.WindowEvent e) {
                java.awt.EventQueue.invokeLater(() -> centerContent());
            }
        });
        
        // Center content initially after window is shown
        java.awt.EventQueue.invokeLater(() -> centerContent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        lbTexto2 = new javax.swing.JLabel();
        lbHotelGales = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbBienvenido = new javax.swing.JLabel();
        lbTexto1 = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lbContraseña = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        chkRecordarme = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        itemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTexto2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbTexto2.setForeground(new java.awt.Color(255, 255, 255));
        lbTexto2.setText("Su escape de lujo comienza aqui");
        jPanel1.add(lbTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 250, 30));

        lbHotelGales.setBackground(new java.awt.Color(51, 51, 51));
        lbHotelGales.setFont(new java.awt.Font("Swis721 Blk BT", 1, 36)); // NOI18N
        lbHotelGales.setForeground(new java.awt.Color(255, 255, 255));
        lbHotelGales.setText("  Hotel Gales");
        lbHotelGales.setFocusable(false);
        lbHotelGales.setOpaque(true);
        jPanel1.add(lbHotelGales, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen login 4 .png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setFocusable(false);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, -1));

        desktopPane.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 500));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbBienvenido.setFont(new java.awt.Font("Segoe UI Semibold", 1, 32)); // NOI18N
        lbBienvenido.setForeground(new java.awt.Color(0, 102, 153));
        lbBienvenido.setText("    BIENVENIDO");
        jPanel2.add(lbBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 247, 73));

        lbTexto1.setFont(new java.awt.Font("Serif", 1, 13)); // NOI18N
        lbTexto1.setText("      Por favor, ingrese sus crendenciales para continuar");
        jPanel2.add(lbTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 20));

        lbUsuario.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbUsuario.setText("USUARIO");
        jPanel2.add(lbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 100, 40));

        txtUsuario.addActionListener(this::txtUsuarioActionPerformed);
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 300, 50));

        lbContraseña.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        lbContraseña.setText("CONTRASEÑA");
        jPanel2.add(lbContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 40));
        jPanel2.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 300, 50));

        chkRecordarme.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        chkRecordarme.setText("Recordarme");
        jPanel2.add(chkRecordarme, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Iniciar Sesion");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 290, 50));

        jButton2 = new javax.swing.JButton();
        jButton2.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        jButton2.setText("Crear cuenta");
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 290, 30));

        desktopPane.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 330, 500));

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        itemExit.setMnemonic('x');
        itemExit.setText("Exit");
        itemExit.addActionListener(this::itemExitActionPerformed);
        fileMenu.add(itemExit);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        
        // Make window resizable and set larger initial size
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(1000, 700));
        setLocationRelativeTo(null);
        setTitle("Hotel Gales - Login");
        
        // Ensure desktopPane fills the entire window
        desktopPane.setSize(getContentPane().getSize());
    }// </editor-fold>//GEN-END:initComponents

    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        int opcion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Desea salir de la aplicación?",
                "Confirmar salida",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE);
        if (opcion == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_itemExitActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the FlatDarkLaf look and feel and premium UI settings */
        try {
            javax.swing.UIManager.put( "Button.arc", 15 );
            javax.swing.UIManager.put( "Component.arc", 15 );
            javax.swing.UIManager.put( "TextComponent.arc", 15 );
            javax.swing.UIManager.put( "ScrollBar.thumbArc", 999 );
            javax.swing.UIManager.put( "ScrollBar.thumbInsets", new java.awt.Insets( 2, 2, 2, 2 ) );
            javax.swing.UIManager.setLookAndFeel(new com.formdev.flatlaf.FlatDarkLaf());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MDILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MDILogin login = new MDILogin();
                login.setVisible(true);
                
                // Inicializar el controlador
                new Controlador.ControladorLogin(login);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox chkRecordarme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBienvenido;
    private javax.swing.JLabel lbTexto1;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbHotelGales;
    private javax.swing.JLabel lbTexto2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

    // Métodos getters para el controlador
    public javax.swing.JButton getJButton1() {
        return jButton1;
    }

    public javax.swing.JTextField getTxtUsuario() {
        return txtUsuario;
    }

    public javax.swing.JPasswordField getTxtContraseña() {
        return txtContraseña;
    }

    public javax.swing.JCheckBox getChkRecordarme() {
        return chkRecordarme;
    }

    public javax.swing.JButton getJButton2() {
        return jButton2;
    }

    private void centerContent() {
        java.awt.Container content = getContentPane();
        int contentWidth = content.getWidth();
        int contentHeight = content.getHeight();
        
        if (contentWidth <= 0 || contentHeight <= 0) return;
        
        int panelWidth = contentWidth / 2;
        int panelHeight = contentHeight;
        
        // Update outer panels to fill the window
        org.netbeans.lib.awtextra.AbsoluteLayout desktopLayout =
            (org.netbeans.lib.awtextra.AbsoluteLayout) desktopPane.getLayout();
        desktopLayout.addLayoutComponent(jPanel1,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, panelWidth, panelHeight));
        desktopLayout.addLayoutComponent(jPanel2,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(panelWidth, 0, contentWidth - panelWidth, panelHeight));
        
        // --- Reposition components inside jPanel1 (left: branding) ---
        org.netbeans.lib.awtextra.AbsoluteLayout layout1 =
            (org.netbeans.lib.awtextra.AbsoluteLayout) jPanel1.getLayout();
        
        // Background image fills the panel
        layout1.addLayoutComponent(jLabel1,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, panelWidth, panelHeight));
        
        // Hotel name centered
        int hotelW = 280;
        int hotelH = 70;
        int hotelX = Math.max(20, (panelWidth - hotelW) / 2);
        int hotelY = Math.max(180, panelHeight / 3 - hotelH);
        layout1.addLayoutComponent(lbHotelGales,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(hotelX, hotelY, hotelW, hotelH));
        
        // Tagline centered below hotel name
        int tagW = 250;
        int tagH = 30;
        int tagX = Math.max(40, (panelWidth - tagW) / 2);
        layout1.addLayoutComponent(lbTexto2,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(tagX, hotelY + hotelH + 10, tagW, tagH));
        
        // --- Reposition components inside jPanel2 (right: login form) ---
        org.netbeans.lib.awtextra.AbsoluteLayout layout2 =
            (org.netbeans.lib.awtextra.AbsoluteLayout) jPanel2.getLayout();
        
        // Form group height is ~500px; vertically center it if panel is taller
        int formH = 500;
        int offsetY = Math.max(0, (panelHeight - formH) / 2);
        
        layout2.addLayoutComponent(lbBienvenido,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(40, offsetY + 10, 247, 73));
        layout2.addLayoutComponent(lbTexto1,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(10, offsetY + 80, 320, 20));
        layout2.addLayoutComponent(lbUsuario,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(20, offsetY + 120, 100, 40));
        layout2.addLayoutComponent(txtUsuario,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(20, offsetY + 160, 300, 50));
        layout2.addLayoutComponent(lbContraseña,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(20, offsetY + 240, 130, 40));
        layout2.addLayoutComponent(txtContraseña,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(20, offsetY + 280, 300, 50));
        layout2.addLayoutComponent(chkRecordarme,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(20, offsetY + 350, -1, -1));
        layout2.addLayoutComponent(jButton1,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(20, offsetY + 400, 290, 50));
        layout2.addLayoutComponent(jButton2,
            new org.netbeans.lib.awtextra.AbsoluteConstraints(20, offsetY + 460, 290, 30));
        
        desktopPane.revalidate();
        desktopPane.repaint();
    }

}
