/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package vista;

/**
 *
 * @author alejo
 */
public class MDIPrincipal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MDIPrincipal.class.getName());


    /**
     * Creates new form MDIPrueba
     */
    public MDIPrincipal() {
        initComponents();
        // 1. Cargamos la imagen desde tu paquete (reemplaza 'imagenes' y 'tu_imagen.png' con tus nombres)
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        mnuBar = new javax.swing.JMenuBar();
        mnuArchivo = new javax.swing.JMenu();
        mnuSalir = new javax.swing.JMenuItem();
        mnuRecepcion = new javax.swing.JMenu();
        mnuHabitaciones = new javax.swing.JMenu();
        mnuGestionarHabitaciones = new javax.swing.JMenuItem();
        mnuGestionarClientes = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        mnuReservas = new javax.swing.JMenu();
        mnuGestionarReservas = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenu();
        mnuGestionarEmpleados = new javax.swing.JMenuItem();
        mnuAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        mnuArchivo.setText("Archivo");

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(this::mnuSalirActionPerformed);
        mnuArchivo.add(mnuSalir);

        mnuBar.add(mnuArchivo);

        mnuRecepcion.setText("Recepcion");
        mnuBar.add(mnuRecepcion);

        mnuHabitaciones.setText("Habitaciones");

        mnuGestionarHabitaciones.setText("Gestionar Habitaciones");
        mnuHabitaciones.add(mnuGestionarHabitaciones);

        mnuBar.add(mnuHabitaciones);

        mnuGestionarClientes.setText("Clientes");

        jMenuItem3.setText("Gestionar Clientes");
        mnuGestionarClientes.add(jMenuItem3);

        mnuBar.add(mnuGestionarClientes);

        mnuReservas.setText("Reservas");

        mnuGestionarReservas.setText("Gestionar Reservas");
        mnuReservas.add(mnuGestionarReservas);

        mnuBar.add(mnuReservas);

        mnuEmpleados.setText("Empleados");

        mnuGestionarEmpleados.setText("Gestionar Empleados");
        mnuEmpleados.add(mnuGestionarEmpleados);

        mnuBar.add(mnuEmpleados);

        mnuAyuda.setText("Ayuda");
        mnuBar.add(mnuAyuda);

        setJMenuBar(mnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed

        System.exit(0);
    }//GEN-LAST:event_mnuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MDIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem MenuAutos;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu mnuArchivo;
    private javax.swing.JMenu mnuAyuda;
    private javax.swing.JMenuBar mnuBar;
    private javax.swing.JMenu mnuEmpleados;
    private javax.swing.JMenu mnuGestionarClientes;
    private javax.swing.JMenuItem mnuGestionarEmpleados;
    private javax.swing.JMenuItem mnuGestionarHabitaciones;
    private javax.swing.JMenuItem mnuGestionarReservas;
    private javax.swing.JMenu mnuHabitaciones;
    private javax.swing.JMenu mnuRecepcion;
    private javax.swing.JMenu mnuReservas;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables

}
